// src/constants/permissions.js
// Single source of truth for every permission string used in Sidebar.jsx and MainRoutes.jsx.
// These MUST match exactly (case-sensitive) what the backend embeds in the JWT's
// `permissions` array. If backend renames/adds a permission, fix it here once.

export const PERMISSIONS = {
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',

  USER_VIEW: 'USER_VIEW',

  TEACHER_VIEW: 'TEACHER_VIEW',

  STUDENT_VIEW: 'STUDENT_VIEW',

  ACADEMIC_VIEW: 'ACADEMIC_VIEW',
  ACADEMIC_YEAR_MANAGE: 'ACADEMIC_YEAR_MANAGE',

  HOMEWORK_VIEW: 'HOMEWORK_VIEW',

  TIMETABLE_VIEW: 'TIMETABLE_VIEW',
  TIMETABLE_MANAGE: 'TIMETABLE_MANAGE',

  EXAM_VIEW: 'EXAM_VIEW',
  EXAM_MARKS_VIEW_CLASS: 'EXAM_MARKS_VIEW_CLASS',
  EXAM_MARKS_ENTER: 'EXAM_MARKS_ENTER',
  EXAM_APPROVE: 'EXAM_APPROVE',
  EXAM_CREATE: 'EXAM_CREATE',

  CIRCULAR_CREATE: 'CIRCULAR_CREATE',
  CIRCULAR_APPROVE: 'CIRCULAR_APPROVE',
  CIRCULAR_DELETE: 'CIRCULAR_DELETE',

  EVENT_CREATE: 'EVENT_CREATE',
  EVENT_APPROVE: 'EVENT_APPROVE',
  EVENT_DELETE: 'EVENT_DELETE',

  NOTICE_VIEW: 'NOTICE_VIEW',

  ATTENDANCE_VIEW: 'ATTENDANCE_VIEW',
  ATTENDANCE_CREATE: 'ATTENDANCE_CREATE',
  ATTENDANCE_EDIT: 'ATTENDANCE_EDIT',
  ATTENDANCE_APPROVE: 'ATTENDANCE_APPROVE',

  LEAVE_VIEW: 'LEAVE_VIEW',
  LEAVE_APPROVE: 'LEAVE_APPROVE',
  // NOTE: no dedicated HOLIDAY_MANAGE / LEAVE_CONFIG_MANAGE permission exists yet
  // on the backend (confirmed absent even in SUPER_ADMIN/GLOBAL_ADMIN tokens).
  // Using LEAVE_DELETE as a proxy until backend adds dedicated permissions.
  LEAVE_DELETE: 'LEAVE_DELETE',

  STOCK_OVERVIEW: 'STOCK_OVERVIEW',
  STOCK_REPORT: 'STOCK_REPORT',
  STOCK_ITEM_VIEW: 'STOCK_ITEM_VIEW',
  STOCK_MOVEMENT_VIEW: 'STOCK_MOVEMENT_VIEW',
  STOCK_INWARD: 'STOCK_INWARD',
  STOCK_OUTWARD: 'STOCK_OUTWARD',
  STOCK_TRANSFER: 'STOCK_TRANSFER',
  STORE_VIEW: 'STORE_VIEW',
  CLASS_ITEM_CONFIG_VIEW: 'CLASS_ITEM_CONFIG_VIEW',
  STUDENT_ORDER_VIEW: 'STUDENT_ORDER_VIEW',

  TRANSPORT_VIEW: 'TRANSPORT_VIEW',
  TRANSPORT_EDIT: 'TRANSPORT_EDIT',

  FEE_VIEW: 'FEE_VIEW',
  FEE_COLLECT: 'FEE_COLLECT',
  FEE_STRUCTURE_VIEW: 'FEE_STRUCTURE_VIEW',
  FEE_STRUCTURE_MANAGE: 'FEE_STRUCTURE_MANAGE',
  FEE_PERIOD_VIEW: 'FEE_PERIOD_VIEW',
  FEE_PERIOD_MANAGE: 'FEE_PERIOD_MANAGE',

  PAYROLL_VIEW: 'PAYROLL_VIEW',
};

// These two screens stay ROLE-locked on purpose, not permission-gated.
// Letting a custom role grant itself access to the role-editor or school-config
// screen via its own permission set would be a privilege-escalation hole.
export const SYSTEM_ROLES = {
  ROLE_MANAGE: ['GLOBAL_ADMIN'],
  SCHOOL_CONFIG_MANAGE: ['SUPER_ADMIN', 'GLOBAL_ADMIN'],
  SCHOOL_SWITCHER: ['SUPER_ADMIN', 'GLOBAL_ADMIN'],
  SCHOOL_PICKER: ['SUPER_ADMIN', 'GLOBAL_ADMIN'],
};