export const COMMON_STATUS = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    PUBLISHED: 'PUBLISHED',
    CANCELLED: 'CANCELLED',
};

export const HOMEWORK_CONSTS = {
    PAGE_TITLE: "Homework Management",
    ERRORS: {
        FALLBACK: "Something went wrong",
        LOAD_TEACHERS: "Failed to load teachers",
        LOAD_CLASSES: "Failed to load classes",
        LOAD_SECTIONS: "Failed to load sections",
        LOAD_SUBJECTS: "Failed to load subjects",
        LOAD_HOMEWORK: "Failed to load homework",
        SAVE_HOMEWORK: "Failed to save homework",
        CANCEL_HOMEWORK: "Failed to cancel homework",
    },
    SUCCESS: {
        UPDATED: "Homework updated!",
        PUBLISHED: "Homework published!",
        CANCELLED: "Homework cancelled",
    },
    WARNINGS: {
        SELECT_FIRST: "Please select a class and section first.",
    },
    CONFIRM: {
        CANCEL_MSG: "Are you sure you want to cancel this homework? This action cannot be undone.",
    },
};

export const CLASS_SEC_CONSTS = {
    GRADE_OPTIONS: [
        { value: 0, label: 'PG' },
        ...Array.from({ length: 12 }, (_, i) => ({ value: i + 1, label: `${i + 1}` })),
        { value: 13, label: 'Grade 13' },
        { value: 14, label: 'Grade 14' },
        { value: 15, label: 'Grade 15' },
    ],
    GRADE_COLORS: [
        'bg-pink-50 text-pink-700', 'bg-red-50 text-red-700', 'bg-orange-50 text-orange-700',
        'bg-amber-50 text-amber-700', 'bg-yellow-50 text-yellow-700', 'bg-lime-50 text-lime-700',
        'bg-green-50 text-green-700', 'bg-teal-50 text-teal-700', 'bg-cyan-50 text-cyan-700',
        'bg-sky-50 text-sky-700', 'bg-blue-50 text-blue-700', 'bg-indigo-50 text-indigo-700',
        'bg-violet-50 text-violet-700', 'bg-purple-50 text-purple-700', 'bg-fuchsia-50 text-fuchsia-700',
        'bg-rose-50 text-rose-700',
    ],
    TEXT: {
        TITLE: "Class & Section Configuration",
        SUBTITLE: "Manage classes and their sections for your school",
        SEC_CONFIG_SUB: "Sections Configuration",
        NO_CLASSES: "No classes found",
        NO_CLASSES_SUB: 'Click "Add Class" to create your first class',
        NO_SECTIONS: "No sections found",
        NO_SECTIONS_SUB: 'Click "Add Section" to create the first section',
        ACTIVE: "Active",
        INACTIVE: "Inactive",
        EDIT: "Edit",
        CANCEL: "Cancel",
        CONFIRM: "Confirm",
        STATUS: "Status",
        DESCRIPTION: "Description",
        NO_DESC: "No description provided.",
        DISPLAY_ORDER: "Display Order",
        ALL_STATUS: "All Status",
        FALLBACK_DASH: "—",
        CLASS_DETAILS: "Class Details",
        TOTAL_SECTIONS: "Total Sections",
        GRADE_LEVEL: "Grade Level",
        LEVEL_PREFIX: "(Level ",
        LEVEL_SUFFIX: ")",
        MANAGE_SECTIONS: "Manage Sections",
        ADD_CLASS: "Add Class",
        EDIT_CLASS: "Edit Class",
        CLASS_NAME: "Class Name",
        PH_CLASS_NAME: "e.g. Class X, Grade 5, LKG",
        SELECT_GRADE: "— Select grade —",
        PH_CLASS_DESC: "Optional notes about this class",
        PH_ORDER_CLASS: "e.g. 10",
        CREATE_CLASS: "Create Class",
        SAVE_CHANGES: "Save Changes",
        ADD_SECTION: "Add Section",
        EDIT_SECTION: "Edit Section",
        SECTION_NAME: "Section Name",
        PH_SEC_NAME: "e.g. A, B, Science",
        ROOM_NUMBER: "Room Number",
        PH_ROOM: "e.g. 101, Lab-3",
        CAPACITY: "Capacity",
        PH_CAPACITY: "Max students",
        CLASS_TEACHER: "Class Teacher",
        LOADING_TEACHERS: "Loading...",
        NO_TEACHER_ASSIGNED: "No teacher assigned",
        SELECT_TEACHER_PREFIX: "— ",
        SELECT_TEACHER_SUFFIX: " —",
        PH_SEC_DESC: "Optional notes",
        PH_ORDER_SEC: "e.g. 1",
        CREATE_SECTION: "Create Section",
        SEARCH_CLASS_PH: "Search by class name...",
        SEARCH_SEC_PH: "Search by section name or room...",
        ALL_GRADES: "All Grades",
        SEARCH_BTN: "Search",
        TH_CLASS_NAME: "Class Name",
        TH_GRADE: "Grade",
        TH_DESC: "Description",
        TH_SECTIONS: "Sections",
        TH_STATUS: "Status",
        TH_ACTIONS: "Actions",
        BTN_VIEW: "View",
        ADD_SECTIONS_BTN: "Add Sections",
        TH_SECTION: "Section",
        TH_ROOM: "Room",
        TH_CAP_ENR: "Capacity / Enrolled",
        TH_CLASS_TEACHER: "Class Teacher",
        LBL_TEACHER: "Teacher: ",
        CARD_TOTAL_CLASSES: "Total Classes",
        CARD_ACTIVE_CLASSES: "Active Classes",
        CARD_GRADE_RANGE: "Grade Range",
        CARD_SECTIONS: "Sections",
        CARD_CAPACITY: "Total Capacity",
        CARD_ENROLLED: "Enrolled",
        CARD_OCCUPANCY: "Occupancy",
    },
    ERRORS: {
        NO_SCHOOL_ID: "School ID not found — please re-login",
        LOAD_CLASSES: "Failed to load classes",
        LOAD_SECTIONS: "Failed to load sections",
        SAVE_CLASS: "Failed to save class",
        SAVE_SECTION: "Failed to save section",
        PROCEED: "Failed to proceed",
    },
    SUCCESS: {
        CLASS_CREATED: (name) => `${name} created successfully`,
        CLASS_UPDATED: (name) => `${name} updated successfully`,
        SEC_CREATED: (name) => `Section ${name} created successfully`,
        SEC_UPDATED: (name) => `Section ${name} updated successfully`,
        CLASS_PROCESSED: (name) => `${name} status processed successfully`,
        SEC_INACTIVE: (name) => `Section ${name} marked inactive successfully`,
    },
    VALIDATION: {
        CLASS_NAME_REQ: "Class name is required",
        SEC_NAME_REQ: "Section name is required",
        MAX_50: "Max 50 characters",
        GRADE_REQ: "Grade level is required",
        GRADE_RANGE: "Must be 0–15",
        CAP_MIN: "Must be ≥ 1",
        MAX_500: "Max 500 characters",
    },
    DELETE: {
        CLASS_TITLE: "Move to Inactive",
        CLASS_MSG: (name) => `Are you sure you want to mark "${name}" as Inactive?`,
        CLASS_SUB: "This configuration won't be displayed on operational workflows.",
        SEC_TITLE: "Move Section to Inactive",
        SEC_MSG: (name) => `Are you sure you want to mark Section "${name}" as Inactive?`,
        SEC_SUB: (enr) => `This configuration won't be displayed on active workflows (${enr} currently enrolled).`,
    },
};

export const SEC_SUB_CONSTS = {
    TEXT: {
        EMPTY_SEC_DTL: "Select section to load details.",
        EMPTY_SUB_DTL: "No matching subject details located.",
        EMPTY_VIEW_ASS: "Select a section to view assignments.",
        EMPTY_NO_MATCH: "No records match search selection parameters.",
        CLASS: "Class",
        SECTION: "Section",
        ASSIGN_SUBJECTS: "Assign Subjects",
        SECTION_SUBJECTS: "Section Subjects",
        EDIT_ASSIGNMENT: "Edit Assignment",
        SUBJECT: "Subject",
        WEEKLY_HOURS: "Weekly Hours",
        HRS: "hrs",
        ALL_STATUS: "All Status",
        ACTIVE_ONLY: "Active Only",
        SEARCH_PLACEHOLDER: "Search subject code...",
        SELECT_SUBJECT: "— Select Subject —",
        MANDATORY: "Mandatory",
        OPTIONAL: "Optional",
        ACTIVE: "Active",
        INACTIVE: "Inactive",
        EDIT: "Edit",
        REMOVE: "Remove",
        ADD_ANOTHER: "+ Add Another Subject",
        CANCEL: "Cancel",
        SAVE_CHANGES: "Save Changes",
        CONFIRM: "Confirm",
        LOADING: "Loading…",
        SAVING: "Saving…",
        REMOVING: "Removing…",
        FALLBACK_DASH: "—",
    },
    HEADERS: ["Subject", "Code", "Weekly Hours", "Mandatory", "Status", "Actions"],
    CONFIRM: {
        REMOVE: (name) => `Remove "${name}" from this section?`,
    },
};

export const EXAM_CONSTS = {
    VALIDATION: {
        REQ_MIN_1: "Required, min 1",
        REQUIRED: "Required",
        EXCEEDS_MAX: (max) => `Cannot exceed ${max}`,
        TP_SUM: (max) => `Theory+Practical must = ${max}`,
        MAX_LIMIT: (max) => `Max ${max}`,
    },
    ADD_SUBJECT: {
        TITLE_EDIT: "Edit Subject Config",
        TITLE_ADD: "Add Subjects to Exam",
        TP_BREAKDOWN: "Theory / Practical Breakdown",
        MAX_THEORY: "Max Theory *",
        MAX_PRACTICAL: "Max Practical *",
        PASS_THEORY: "Pass Theory",
        PASS_PRACTICAL: "Pass Practical",
        MATCHES_MAX: "✓ Matches max marks",
        MUST_EQUAL: (max) => `Must equal ${max || "max marks"}`,
        NO_CLASS_SELECTED: "No class selected. Please select an exam first.",
        NO_SUBJECTS_MAPPED: "No subjects mapped to this class yet.",
        LOAD_FAIL: "Failed to load subjects. Please close and try again.",
        FIX_ERRORS: "Please fix the errors above.",
        SELECT_AT_LEAST_ONE: "Please select at least one subject to add.",
        FIX_HIGHLIGHTED: "Please fix the errors in the highlighted rows.",
        SKIPPED: (count) => `${count} subject(s) were already added and skipped.`,
        SAVE_FAIL: "Failed to save subjects. Please try again.",
        NO_SUBJECTS_AVAIL: "No subjects available for this class.",
        SELECT_ALL: "Select All",
        SELECTED: "selected",
        ALREADY_ADDED: "already added",
        ALREADY_ADDED_BADGE: "Already added to this exam",
        ADDED_SHORT: "Added",
        TOTAL: "total",
        SUBJECT: "Subject",
        MAX_MARKS: "Max Marks *",
        PASS_MARKS: "Pass Marks *",
        TP_COL: "Theory + Practical",
        HAS_TP_SPLIT: "Has Theory + Practical Split",
        ENABLE_TP_SPLIT: "Enable separate breakdown for theory and practical marks",
        CANCEL: "Cancel",
        SAVE_CHANGES: "Save Changes",
        ADD_SUBJECT_BTN: "Add Subject",
        ADDING: "Adding…",
        SAVING: "Saving…",
        SPLIT: "Split",
    },
    UPDATE_SUBJECT: {
        TITLE: "Update Subject Config",
        INFO_PREFIX: "Updates are only allowed if ",
        INFO_BOLD: "no marks have been entered",
        INFO_SUFFIX: " for any subject in this exam. All ",
        INFO_END: " will be updated together.",
        NO_SUBJECTS: "No subjects configured for this exam yet.",
        UPDATING_COUNT: "Updating ",
        BTN_UPDATING: "Updating…",
        BTN_UPDATE: "Update Subject",
        ERR_UPDATE_FAIL: "Failed to update subjects. Please try again.",
    },
    ANALYTICS: {
        TITLE: "Exam Analytics Dashboard",
        TOOLTIP: "Comprehensive high-fidelity academic tracking.",
        CASCADE_FILTER: "Cascade Filter Framework",
        LBL_ACADEMIC_YEAR: "Academic Year",
        LBL_CLASS: "Class",
        LBL_EXAM: "Exam",
        LBL_SECTION: "Section",
        LBL_SUBJECT: "Subject",
        OPTIONAL: "optional",
        SELECT_CLASS: "Select Class",
        SELECT_EXAM: "Select Exam",
        ALL_SECTIONS: "All Sections",
        ALL_SUBJECTS: "All Subjects",
        APPLY_SYNC: "Apply Sync",
        LOADING: "Loading…",
        ISOLATE_CONTEXT: "Isolate context filters above to build visualization reporting elements.",
        EVENT_SUMMARY: "Event Summary — ",
        ALL_CLASSES: "All Classes",
        CLASSES: "Classes",
        SECTIONS: "Sections",
        OVERALL_PASS: "Overall Pass Rate",
        SCHOOL_AVG: "School Avg",
        PASS_RATE_BY_CLASS: "Pass Rate By Class",
        RESULT_UNDECLARED: "Result Undeclared",
        PERF_TREND: "Performance Trend — ",
        NOW: "← now",
        UNDECLARED_TIMELINE: "Undeclared Timeline Block",
        CLASS_AVG: "Class Average",
        HIGH_SCORE: "Highest Score",
        FAILED_STUDENTS: "Failed Students",
        PASS_RATE: "Pass Rate",
        WEAKEST_SUB: "Weakest Subject",
        AWAITING: "Awaiting selection",
        OF_TOTAL_LAYOUT: " of total layout",
        OF: " of ",
        VERIFIED: " verified",
        AVG: "Avg ",
        FAIL: " fail",
        SUB_WISE_AVG: "Subject-wise Average %",
        AVG_PCT: "Avg %",
        PASS_LINE: "Pass line",
        NO_SUB_METRICS: "No subject metrics accessible.",
        PASS_FAIL_SUB: "Pass / Fail per Subject",
        MAX: "Max",
        PASS: "Pass",
        ABS: "Abs",
        NO_DATA: "No data mapped.",
        GRADE_DIST: "Grade Distribution",
        GRADE_MISSING: "Grade metrics mapping missing variables.",
        TOTAL_VERIFIED: " students verified",
        TOTAL: "Total: ",
        SEC_WISE_COMP: "Section-wise Comparison",
        SELECT_ALL_SEC_VIS: "Select \"All Sections\" context filters to visualize comparative rows.",
        NO_COMP_ROWS: "No comparative rows generated.",
        STUDENTS: "Students",
        HIGH: "High",
        LOW: "Low",
        BEST_AVG: "Best Avg",
        CLASS_TOTAL: "Class Total",
        TOP_PERFORMERS: "Top Performers",
        RANK: "Rank",
        STUDENT: "Student",
        ADM_NO: "Adm No",
        SEC_RANK: "Sec Rank",
        PERCENTAGE: "Percentage",
        GRADE: "Grade",
        NO_PARAMS: "No parameters loaded.",
        FAILED_IN: "Failed In",
        ALL_PASSED: "All profiles passed parameters.",
        ERR_META: "Failed to initialize system context targets.",
        ERR_EXAMS: "Error parsing fields for targeted class layout.",
        ERR_SYNC: "Data sync fault. Request manual refresh step.",
        CONTEXT: "Context:",
        RES_NOT_DEC: "Results Not Declared",
        CLASS_ANA_AVAIL: "Class analytics will be available after results are declared.",
        FALLBACK_DASH: "—"
    },
    CONFIG: {
        TITLE: "Exam Configuration",
        SUBTITLE: "Manage grading scales and exam type definitions",
        TAB_GRADE: "Grade Config",
        TAB_EXAM: "Exam Type",
        CONFIRM_DEL_TITLE: "Confirm Delete",
        CONFIRM_DEL_MSG: "Are you sure you want to delete this record? This action cannot be undone.",
        CANCEL: "Cancel",
        DELETE: "Delete",
        GRADE_SCALE_CONF: "Grading Scale Configuration",
        ADD_GRADE_BAND: "Add Grade Band",
        TH_GRADE: "Grade",
        TH_MIN_PCT: "Min %",
        TH_MAX_PCT: "Max %",
        TH_DESC: "Description",
        TH_STATUS: "Status",
        TH_ACTIONS: "Actions",
        NO_GRADES: "No grade bands configured yet.",
        ACTIVE: "Active",
        INACTIVE: "Inactive",
        EDIT: "Edit",
        EDIT_GRADE_BAND: "Edit Grade Band",
        GRADE_NAME: "Grade Name",
        PH_GRADE_NAME: "Enter grade name",
        MIN_PCT: "Min Percentage",
        MAX_PCT: "Max Percentage",
        UPDATE: "Update",
        EXAM_TYPE_MASTER: "Exam Types Master",
        ADD_EXAM_TYPE: "Add Exam Type",
        TH_NO: "#",
        TH_NAME: "Name",
        NO_EXAM_TYPES: "No exam types configured yet.",
        DEACTIVATE: "Deactivate",
        ACTIVATE: "Activate",
        EDIT_EXAM_TYPE: "Edit Exam Type",
        EXAM_TYPE_NAME: "Exam Type Name",
        PH_EXAM_NAME: "Enter Exam Name...",
        PH_EXAM_DESC: "Enter Exam Description...",
        ERR_LOAD_GRADES: "Failed to load grade configs",
        ERR_GRADE_REQ: "Grade name is required",
        ERR_MIN_PCT: "Enter valid min % (0-100)",
        ERR_MAX_PCT: "Enter valid max % (0-100)",
        ERR_DESC_REQ: "Description is required",
        SUCC_GRADE_UPD: "Grade updated successfully!",
        SUCC_GRADE_CRE: "Grade created successfully!",
        ERR_OP_FAIL: "Operation failed. Please try again.",
        SUCC_GRADE_DEL: "Grade deleted successfully!",
        ERR_DEL_FAIL: "Delete failed. Please try again.",
        ERR_LOAD_TYPES: "Failed to load exam types",
        ERR_TYPE_REQ: "Exam type name is required",
        SUCC_TYPE_UPD: "Exam type updated!",
        SUCC_TYPE_CRE: "Exam type created!",
        SUCC_TYPE_STAT: (isActive) => `Exam type ${isActive ? "deactivated" : "activated"} successfully!`,
        ERR_STAT_UPD: "Status update failed."
    },
    EXAMS: {
        TITLE: "Exam Events",
        TOOLTIP: "Manage school-wide exam events across classes.",
        ERR_FILTERS: "Failed to load filters. Please refresh.",
        ALL_YEARS: "All Years",
        ALL_TYPES: "All Exam Types",
        ALL_CLASSES: "All Classes",
        ALL_STATUSES: "All Statuses",
        BTN_EXPORT: "Export Schedule",
        BTN_EXPORT_MOB: "Export",
        BTN_NEW: "New Exam Event",
        BTN_NEW_MOB: "New",
        ERR_LOAD_EVENTS: "Failed to load exam events.",
        NO_EVENTS: "No exam events found. Create one to get started.",
        STATUS: {
            DECLARED: "Declared",
            PARTIAL: "Partial",
            SCHEDULED: "Scheduled",
            READY: "Ready",
            PENDING: "Pending",
            NOT_STARTED: "Not started"
        },
        STATS: {
            EVENTS: "Total Events",
            EVENTS_SUB: "Scheduled",
            DECLARED: "Fully Declared",
            DECLARED_SUB: "All results in",
            PENDING: "Pending",
            PENDING_SUB: "Awaiting",
            ALL_CLEAR: "All clear",
            CLASSES: "Classes Covered",
            NONE_YET: "None yet"
        },
        ACTIONS: {
            REPORTS: "Reports",
            SUBJECTS: "Subjects",
            MARKS: "Marks",
            ENTER_MARKS: "Enter Marks",
            DECLARE: "Declare",
            REMOVE: "Remove",
            EDIT: "Edit",
            COPY: "Copy",
            ADD_CLASS: "Add Class to Event"
        },
        MODALS: {
            DECLARE_TITLE: "Declare Result",
            DECLARE_MSG1: "Declaring result for:",
            DECLARE_MSG2: "This will permanently lock all marks and cannot be undone.",
            BTN_DECLARE: "Yes, Declare",
            BTN_DECLARING: "Declaring…",
            REMOVE_TITLE: "Remove Class",
            REMOVE_MSG: "from this exam event? This deletes its subject configs too.",
            BTN_REMOVE: "Remove",
            BTN_REMOVING: "Removing…",
            EDIT_TITLE: "Edit Exam Event",
            EVENT_NAME: "Event Name",
            START_DATE: "Start Date",
            END_DATE: "End Date",
            DESC: "Description",
            BTN_SAVE: "Save Changes",
            BTN_SAVING: "Saving…",
            COPY_TITLE: "Copy Exam Event",
            COPY_MSG1: "Copies classes & subject configs from",
            EXAM_TYPE: "Exam Type",
            ACADEMIC_YEAR: "Academic Year",
            NEW_EVENT_NAME: "New Event Name",
            PH_AUTO_GEN: "Auto-generated if blank",
            BTN_COPY: "Create Copy",
            BTN_COPYING: "Copying…",
            ADD_TITLE: "Add Class to Event",
            ADD_MSG_NO_CLASS: "All classes are already part of this event.",
            BTN_ADD: (count) => `Add ${count || ""} Class${count === 1 ? "" : "es"}`,
            BTN_ADDING: "Adding…",
            SUB_TITLE: (cls) => `Subjects — ${cls}`,
            SUB_NO_SUB: "No subjects configured for this class.",
            MAX: "Max",
            PASS: "Pass",
            CANCEL: "Cancel"
        },
        ERRORS: {
            DECLARE: "Failed to declare result.",
            REMOVE_CLASS: "Failed to remove class.",
            ADD_CLASS: "Failed to add classes.",
            UPDATE_EVENT: "Failed to update event.",
            COPY_EVENT: "Failed to copy event.",
            LOAD_SUB: "Failed to load subjects.",
            REMOVE_SUB: "Failed to remove subject."
        }
    },
    MARKS_ENTRY: {
        TITLE: "Manage Marks Entry",
        TOOLTIP: "Enter and manage student marks.",
        PH_CLASS: "Select Class",
        PH_SECTION: "Select Section",
        PH_EXAM: "Select Exam",
        PH_SUBJECT: "Select Subject",
        LOADING: "Loading...",
        LOADING_EXAMS: "Loading exams...",
        LOADING_SUBJECTS: "Loading subjects...",
        FETCHING_MSG: "Fetching student marks sheet automatically...",
        SELECT_PROMPT: "Select a Class, Section, Exam and Subject. The sheet will load automatically.",
        SHEET_TITLE: "Marks Sheet",
        MAX: "Max",
        PASS: "Pass",
        TH_PR_LBL: (th, pr) => `Th ${th} + Pr ${pr}`,
        STUDENTS: "students",
        MARKS_SAVED: "Marks Saved",
        UNSAVED_CHANGES: "Unsaved Changes",
        SUCC_SAVED: "Marks saved successfully!",
        BTN_RESET: "Reset",
        BTN_UPDATING: "Updating...",
        BTN_SAVING: "Saving...",
        BTN_UPDATE: "Update Marks",
        BTN_SAVE_BULK: "Save Marks (Bulk)",
        BTN_SAVED: "Saved ✓",
        TH_ROLL: "Roll No.",
        TH_STUDENT: "Student Name",
        TH_ADM: "Adm. No.",
        TH_THEORY: (max) => `Theory (/${max})`,
        TH_PRACTICAL: (max) => `Practical (/${max})`,
        TH_TOTAL: (max) => `Total (/${max})`,
        TH_MARKS: (max) => `Marks (/${max})`,
        TH_ABSENT: "Absent",
        TH_GRADE: "Grade",
        TH_REMARKS: "Remarks",
        PH_REMARKS: "Remarks...",
        ERR_NO_EXAM: "No exam selected.",
        ERR_NO_CONFIG: "Subject config ID not found.",
        ERR_SAVE: "Failed to save marks.",
        ERR_LOAD: "Failed to load marks sheet automatically."
    },
    NEW_EXAM: {
        TITLE: "Create Exam Event",
        STEP_EVENT: "Event Info",
        STEP_CLASSES: "Classes",
        STEP_SUBJECTS: "Subjects",
        STEP_CONFIRM: "Confirm",
        VAL_EXAM_TYPE: "Please select an exam type.",
        VAL_YEAR: "Please select an academic year.",
        VAL_START: "Start date is required.",
        VAL_END: "End date is required.",
        VAL_DATE_ORDER: "Start date cannot be after end date.",
        VAL_CLASS_REQ: "Please select at least one class.",
        VAL_SUB_REQ: "Please select at least one subject.",
        ERR_LOAD_SUB: "Failed to load class subjects.",
        ERR_CREATE: "Failed to create exam event.",
        LBL_EXAM_TYPE: "Exam Type",
        LBL_YEAR: "Academic Year",
        LBL_EVENT_NAME: "Event Name",
        LBL_START: "Start Date",
        LBL_END: "End Date",
        LBL_DESC: "Description",
        PH_NOTES: "Optional notes…",
        PH_SEL_TYPE: "Select type",
        PH_SEL_YEAR: "Select year",
        LBL_SEL_CLASSES: "Select Classes",
        TXT_ONE_EXAM_PER_CLASS: "— one exam created per selected class",
        BTN_SEL_ALL: "Select All",
        BTN_CLEAR: "Clear",
        LBL_DEF_MARKS: "Default Marks",
        TXT_DEF_MARKS_SUB: "— applied to all subjects; override per-subject in next step",
        LBL_MAX: "Max Marks",
        LBL_PASS: "Pass Marks",
        LBL_TP_SPLIT: "Theory + Practical split",
        TXT_DEF_APPLY: "These defaults apply to every subject in every selected class. Fine-tune individual subjects in the next step.",
        TXT_SELECTED_OF: "selected",
        TXT_ALL_CLASSES: "(all classes)",
        TXT_AUTO_LOADED: "Subjects auto-loaded per section",
        TXT_AUTO_DESC: "— sections with identical subjects are shown compactly; sections with different subjects (e.g. streams) are shown per section. Uncheck any subject to exclude it.",
        LBL_QUICK_APPLY: "Quick apply to all:",
        BTN_APPLY_ALL: "Apply to all",
        TXT_SUB_CONFIGS: "section-subject configs across",
        TXT_NO_SEC_SUB: "No sections/subjects found for this class.",
        BTN_ALL: "All ✓",
        BTN_NONE: "None ✗",
        TH_SUBJECT: "Subject",
        TH_MAX: "Max Marks",
        TH_PASS: "Pass Marks",
        TH_TYPE: "Type",
        BTN_FULL: "Full",
        BTN_TP: "T+P",
        LBL_MANUAL_STEPS: "Manual Steps After",
        TH_CLASS: "Class",
        TH_SECTIONS: "Sections",
        TH_SUBJECTS: "Subjects",
        TH_STATUS: "Status",
        TXT_READY: "Ready",
        TXT_NO_SUB: "No subjects",
        BTN_CANCEL: "Cancel",
        BTN_BACK: "Back",
        BTN_NEXT: "Next",
        BTN_CREATING: "Creating…"
    },
    REPORT_CARDS: {
        TITLE: "Manage Report Cards",
        TOOLTIP: "Efficiently manage report cards.",
        STATS: {
            TOTAL: "Total Students",
            PASSED: "Passed",
            FAILED: "Failed",
            ABSENT: "Absent (All)"
        },
        SELECT_ALL_SEC: "All Sections",
        LOADING_EXAMS: "Loading exams...",
        SELECT_EXAM: "Select Exam",
        PENDING: "Pending",
        RELOAD_TITLE: "Reload Data",
        BTN_GENERATE: "Generate All",
        BTN_GENERATING: "Generating...",
        BTN_EXPORT: "Export CSV",
        SUCC_GENERATE: "Report cards generated successfully!",
        ERR_GENERATE: "Failed to generate report cards.",
        ERR_LOAD_CARDS: "Failed to load report cards. Click Generate All first if not yet generated.",
        ERR_LOAD_SINGLE: (name) => `Failed to load report card for ${name}.`,
        LOADING_CARD: "Loading report card...",
        CLASS_RANK: "Class Rank",
        STUDENTS: "students",
        NO_CARDS_FOUND: "No report cards found.",
        PROMPT_GENERATE: "Select an exam and click Generate All or Reload.",
        NO_CARDS_SELECTION: "No report cards found for this selection.",
        BTN_VIEW: "View",
        ROLL: "Roll",
        CSV: {
            TITLE: "Report Cards Export",
            EXAM: "Exam",
            SECTION: "Section",
            TOTAL_STUDENTS: "Total Students",
            HEADERS: ["Rank", "Student Name", "Roll No.", "Admission No.", "Section", "Marks Obtained", "Max Marks", "Percentage", "Grade", "Status"],
            ABSENT: "ABSENT",
            AB: "AB"
        },
        HEADERS: ["Rank", "Student Name", "Roll No.", "Adm. No.", "Section", "Total", "%", "Grade", "Status", "Action"]
    },
    STUDENT_REPORT: {
        TITLE: "Report Card",
        BTN_PRINT: "Print",
        BTN_CLOSE: "Close",
        INFO_TITLE: "Student Information",
        INFO_LABELS: ["Student Name", "Admission No.", "Class", "Section", "Roll No.", "Exam"],
        MARKS_TITLE: "Subject-wise Marks",
        HEADERS: ["Subject", "Max", "Theory", "Practical", "Total", "%", "Grade", "Status"],
        NO_MARKS: "No subject marks available.",
        ABSENT_MARK: "AB",
        ABSENT_LBL: "Absent",
        PASS_LBL: "Pass",
        FAIL_LBL: "Fail",
        TOTAL_MARKS: "Total Marks",
        PERCENTAGE: "Percentage",
        LBL_GRADE: "Grade",
        CLASS_RANK: "Class Rank",
        SEC_RANK: "Section: ",
        RES_ABSENT: "RESULT: ABSENT — Exam not appeared",
        RES_PASSED: "RESULT: PASSED — Promoted to next class",
        RES_FAILED: "RESULT: FAILED — Not promoted",
        REMARKS_TITLE: "Remarks",
        BTN_EDIT: "Edit",
        BTN_ADD_REMARKS: "+ Add Remarks",
        SUCC_REMARKS: "Remarks saved successfully.",
        TEACHER_REMARKS: "Teacher's Remarks",
        PH_TEACHER: "Enter teacher's remarks...",
        NO_REMARKS: "No remarks added yet.",
        PRINCIPAL_REMARKS: "Principal's Remarks",
        PH_PRINCIPAL: "Enter principal's remarks...",
        BTN_CANCEL: "Cancel",
        BTN_SAVING: "Saving...",
        BTN_SAVE_REMARKS: "Save Remarks",
        TEACHER_SIG: "Class Teacher Signature",
        PRINCIPAL_SIG: "Principal Signature",
        GENERATED_BY: "Generated by School Management System",
        PRINT_BTN_FULL: "Print Report Card",
        FALLBACK_SCHOOL: "School Management System",
        FALLBACK_BOARD: "CBSE Affiliated"
    }
};