const SCHOOL_CONFIG_CONST = {
  SCHOOL_CONFIG_TITLE: "School Configuration",
  SCHOOL_CONFIG_SUBTITLE: "Manage school profile, attendance rules & branding",
  TAB_SCHOOL_INFO: "School Info",
  TAB_ATTENDANCE: "Attendance",
  TAB_LOGO: "Logo",
  ERR_SCHOOL_NAME_REQUIRED: "School name is required",
  ERR_SCHOOL_NAME_LENGTH: "Name must be at least 3 characters",
  ERR_SCHOOL_NAME_MAX: "Name must be under 100 characters",
  ERR_SCHOOL_CODE_REQUIRED: "School code is required",
  ERR_SCHOOL_CODE_FORMAT: "Code: 2–20 chars, letters/numbers/_ only",
  ERR_PHONE_INVALID: "Enter a valid phone number (7–15 digits)",
  ERR_EMAIL_INVALID: "Enter a valid email address",
  ERR_YEAR_RANGE: (min, max) => `Year must be between ${min} and ${max}`,
  ERR_PINCODE_LENGTH: "Pincode must be exactly 6 digits",
  ERR_AFFILIATION_LONG: "Affiliation number too long",
  ERR_START_TIME_REQUIRED: "Start time is required",
  ERR_GRACE_PERIOD_RANGE: "Grace period must be 0–120 minutes",
  ERR_THRESHOLD_RANGE: "Threshold must be 0–100%",
  ERR_LATITUDE_REQUIRED: "Latitude is required when GPS is enabled",
  ERR_LATITUDE_RANGE: "Latitude must be between -90 and 90",
  ERR_LONGITUDE_REQUIRED: "Longitude is required when GPS is enabled",
  ERR_LONGITUDE_RANGE: "Longitude must be between -180 and 180",
  ERR_FILE_SIZE_LIMIT: "File size exceeds 5 MB limit",
  ERR_LOAD_CONFIG: "BASIC_INFORMATION_LABEL",
  ERR_FILE_TYPE: "Only JPG, PNG, or WEBP files are accepted",
  STATUS_ACTIVE: "Active",
  STATUS_INACTIVE: "Inactive",
  STATUS_SUSPENDED: "Suspended",
  LOADING_SCHOOL_DETAILS: "Loading school details…",
  FAILED_TO_LOAD_SCHOOLS: "Failed to Load School",
  BASIC_INFORMATION_LABEL: "Basic Information",
  SATURDAY_WORKING_REMARK: "Mark Saturday as a working day for attendance.",
  SUNDAY_WORKING_REMARK: "Mark Sunday as a working day for attendance.",
  ATTENDANCE_RADIUS_REMARK: "Require staff & students to be within radius when marking attendance.",
  DEFINE_ZONE_ATTENDANCE_CORD: "Set school coordinates to define the attendance zone.",
  UPLOAD_INSTRUCTION : "Upload JPG, PNG, or WEBP · Max 5 MB",
  
};


export default SCHOOL_CONFIG_CONST;