const STUDENT_MODULE_STRINGS = {
  COMMON: {
    BACK_TO_LIST: 'Back to List',
    DISCARD_CHANGES: 'Discard Changes',
    CANCEL: 'Cancel',
    LOADING: 'Loading...',
    SAVING: 'Saving...',
    RETRY: 'Retry',
    CHANGE: 'Change',
    REMOVE: 'Remove',
    SELECT: 'Select',
    REQUIRED: 'Required',
    OPTIONAL: 'optional',
    SAVE: 'Save Details',
    READ_ONLY: '(Read-only)',
  },

  GENDER: {
    SELECT: 'Select Gender',
    MALE: 'Male',
    FEMALE: 'Female',
  },

  STUDENTS_LIST: {
    PAGE_TITLE: 'Manage All Students',
    TOOLTIP: 'Efficiently manage all student records, class assignments and account status.',
    SEARCH_PLACEHOLDER: 'Search name, email or admission no…',
    LOADING: 'Loading students…',
    ERROR: 'Error loading students',
    RETRY: 'Retry',
    EMPTY_TITLE: 'No Students Found',
    EMPTY_HELP: 'Try a different search or add a new student.',
    CONTACT_LABEL: 'Contact',
    EMAIL_LABEL: 'Email',
    CLASS_LABEL: 'Class',
    SECTION_LABEL: 'Section',
    STATUS_LABEL: 'Status',
    EDIT: 'Edit',
    VIEW: 'View',
    TOTAL_STUDENTS: 'Total Students',
    ROWS_LABEL: 'Rows per page:',
    ROWS_LABEL_SHORT: 'Rows:',
    PAGE_INFO_PREFIX: 'Showing',
    PAGE_INFO_SEPARATOR: 'to',
    PAGE_INFO_OF: 'of',
    PAGE_LABEL: 'Page',
    TABLE_HEADERS: ['Student Name', 'Mobile Number', 'Email', 'Class', 'Section', 'Status', 'Actions'],
    FILTERS: {
      ALL_CLASSES: 'All Classes',
      ALL_STATUS: 'All Status',
      ACTIVE: 'Active',
      INACTIVE: 'Inactive',
    },
    ACTIONS: {
      ADD_STUDENT: 'Add Student',
      EXPORT_CSV: 'Export CSV',
    },
    EXPORT_SUCCESS: '✓ Exported {count} student{plural} — CSV {page} of {totalPages}',
    EXPORT_EMPTY: 'No students on this page to export.',
    ERROR_LOADING: 'Failed to load students',
    LOADING_DETAILS: 'Loading Student Details...',
  },

  STUDENT_DETAILS: {
    PAGE_TITLE: 'Student Profile',
    LOADING: 'Loading Student Details...',
    ADMISSION_PREFIX: 'Admission No:',
    ROLL_PREFIX: 'Roll No:',
    REMARKS: 'Remarks',
    BADGES: {
      HOSTEL: 'Hostel',
      TRANSPORT: 'Transport',
      REQUIRED: 'Required',
      NOT_REQUIRED: 'Not Required',
    },
    SECTIONS: {
      PERSONAL: 'Personal Details',
      ACADEMIC: 'Academic Details',
      PARENT_GUARDIAN: 'Parent / Guardian Details',
      FACILITIES: 'Facilities',
    },
    FIELD_LABELS: {
      FULL_NAME: 'Full Name',
      GENDER: 'Gender',
      DOB: 'Date of Birth',
      BLOOD_GROUP: 'Blood Group',
      EMAIL: 'Email Address',
      MOBILE: 'Mobile Number',
      ADDRESS: 'Address',
      ADMISSION_NUMBER: 'Admission Number',
      ROLL_NUMBER: 'Roll Number',
      ADMISSION_DATE: 'Admission Date',
      ACADEMIC_YEAR: 'Academic Year',
      PREVIOUS_SCHOOL: 'Previous School',
      CLASS_SECTION: 'Class & Section',
      STATUS: 'Status',
      FATHER_NAME: "Father's Name",
      FATHER_PHONE: "Father's Phone",
      FATHER_OCCUPATION: "Father's Occupation",
      MOTHER_NAME: "Mother's Name",
      MOTHER_PHONE: "Mother's Phone",
      MOTHER_OCCUPATION: "Mother's Occupation",
      GUARDIAN_NAME: 'Guardian Name',
      GUARDIAN_RELATION: 'Guardian Relation',
      EMERGENCY_CONTACT: 'Emergency Contact',
      REMARKS: 'Remarks',
    },
  },

  ADD_STUDENT: {
    PAGE_TITLE: 'Add New Student',
    SUBTITLE: 'Enter the details below to onboard a new student into the system.',
    SAVE: 'Save Details',
    TABS: {
      PERSONAL: 'Personal Details',
      FAMILY: 'Family Details',
    },
    PROFILE_PHOTO_REQUIRED: 'Profile Photo',
    PROFILE_PHOTO_CTA: 'Click to upload photo',
    PROFILE_PHOTO_FORMAT: 'JPEG or PNG, max 10 MB',
    PROFILE_PHOTO_CHANGE: 'Change',
    NEXT: 'Next',
    DISCARD: 'Discard Changes',
    ROLL_LABEL: 'Roll Number',
    ROLL_PLACEHOLDER: 'Enter roll number',
    SUBMIT_LOADING: 'Adding...',
    PROFILE_PHOTO: {
      LABEL: 'Profile Photo',
      CTA: 'Click to upload photo',
      FORMAT_HELP: 'JPEG or PNG, max 10 MB',
      CHANGE: 'Change',
    },
    ERRORS: {
      PHOTO_REQUIRED: 'Please upload a student profile photo!',
      REQUIRED_FIELDS: 'Please fill all required fields!',
      ROLL_REQUIRED: 'Please enter a roll number!',
      SECTION_REQUIRED: 'Please select a section!',
      MOBILE_INVALID: 'Mobile number must be exactly 10 digits!',
      EMAIL_INVALID: 'Please enter a valid student email address!',
      STATUS_INVALID: 'Student status must be ACTIVE to add a new student!',
      DOB_INVALID: 'Date of birth cannot be today or in the future!',
      ADMISSION_DATE_INVALID: 'Admission date cannot be in the future!',
      PHOTO_TYPE: 'Only JPEG or PNG images are allowed!',
      PHOTO_SIZE: 'Image must be smaller than 10 MB!',
    },
    SUCCESS: 'Student added successfully ✅',
    LOADING: 'Adding student...',
  },

  EDIT_STUDENT: {
    PAGE_TITLE: 'Edit Student Details',
    SUBTITLE: 'Update the student information below. Fields marked with * are required.',
    TAB: 'Student Details',
    SUBMIT: 'Update Student',
    SAVE: 'Save Details',
    PROFILE_PHOTO: {
      TITLE: 'Profile Photo',
      CTA: 'Click to upload new photo',
      FORMAT_HELP: 'JPEG or PNG, max 10 MB',
      CURRENT: 'Current profile photo',
      REPLACE: 'Click "Change" to replace',
      NEW_SELECTED: 'new photo selected',
      REFRESH_NOTICE: 'Profile photo may take a few seconds to reflect.',
    },
    ERRORS: {
      PHOTO_TYPE: 'Only JPEG or PNG images are allowed!',
      PHOTO_SIZE: 'Image must be smaller than 10 MB!',
      REQUIRED_FIELDS: 'Please fill all required fields!',
      ROLL_REQUIRED: 'Please enter a roll number!',
      SECTION_REQUIRED: 'Please select a section!',
      MOBILE_INVALID: 'Mobile number must be exactly 10 digits!',
      EMERGENCY_INVALID: 'Emergency contact must be exactly 10 digits!',
      FATHER_PHONE_INVALID: "Father's phone number must be exactly 10 digits!",
      EMAIL_INVALID: 'Please enter a valid email address!',
      LOAD_FAILED: 'Failed to load student details',
      SECTION_LOAD_FAILED: 'Failed to load sections.',
      SECTION_LOAD_RETRY: 'Could not fetch sections. Please refresh.',
    },
    SUCCESS: 'Student updated successfully ✅',
    LOADING: 'Updating student...',
    SECTION_LOADING: 'Loading sections...',
  },

  FAMILY_FORM: {
    FATHER_TITLE: "Father's Details",
    MOTHER_TITLE: "Mother's Details",
    GUARDIAN_TITLE: 'Guardian Details',
    GUARDIAN_HELP: 'Fill this section only if a guardian (other than parents) is responsible for the student.',
    SET_GUARDIAN_TEXT: 'Set Guardian from:',
    USE_FATHER: 'Use Father as Guardian',
    USE_MOTHER: 'Use Mother as Guardian',
    FATHER_NAME: "Father's Name",
    FATHER_OCCUPATION: "Father's Occupation",
    FATHER_PHONE: "Father's Phone",
    FATHER_PHONE_NUMBER: "Father's Phone Number",
    FATHER_EMAIL: "Father's Email",
    MOTHER_NAME: "Mother's Name",
    MOTHER_OCCUPATION: "Mother's Occupation",
    MOTHER_PHONE: "Mother's Phone",
    MOTHER_EMAIL: "Mother's Email",
    GUARDIAN_NAME: "Guardian's Name",
    GUARDIAN_RELATION: 'Relation to Student',
    GUARDIAN_PHONE: "Guardian's Phone",
    GUARDIAN_EMAIL: "Guardian's Email",
    EMERGENCY_CONTACT: 'Emergency Contact Number',
    GUARDIAN_ALERT_FATHER: "Please fill Father's details before setting as Guardian.",
    GUARDIAN_ALERT_MOTHER: "Please fill Mother's details before setting as Guardian.",
    SECTION_TITLE: 'Parent/Guardian Details',
  },

  PERSONAL_FORM: {
    SECTION_TITLE: 'Personal Details',
    FULL_NAME: 'Full Name',
    ROLL_NUMBER: 'Roll Number',
    ROLL_PLACEHOLDER: 'Enter roll number',
    GENDER: 'Gender',
    MOBILE: 'Mobile Number',
    EMAIL: 'Email Address',
    DOB: 'Date of Birth',
    BLOOD_GROUP: 'Blood Group',
    ADMISSION_NUMBER: 'Admission Number',
    SECTION: 'Section',
    ADMISSION_DATE: 'Date of Admission',
    ACADEMIC_YEAR: 'Academic Year',
    PREVIOUS_SCHOOL: 'Previous School',
    STATUS: 'Status',
    ADDRESS: 'Current Address',
    SECTION_LOADING: 'Loading sections...',
    SELECT_SECTION: 'Select Section',
    SELECT_YEAR: 'Select Academic Year',
    CURRENT_YEAR_BADGE: 'Current Academic Year',
    ACTIVE: 'Active',
    INACTIVE: 'Inactive',
    HOSTEL_REQUIRED: 'Hostel Required',
    TRANSPORT_REQUIRED: 'Transport Required',
    HOSTEL_ENABLED: 'Hostel accommodation enabled',
    HOSTEL_DISABLED: 'Hostel accommodation disabled',
    TRANSPORT_ENABLED: 'School transport enabled',
    TRANSPORT_DISABLED: 'School transport disabled',
    ADDITIONAL_REQUIREMENTS: 'Additional Requirements',
    MOBILE_HELP: 'Must be exactly 10 digits',
    MOBILE_HELP_OPTIONAL: 'Must be exactly 10 digits if provided',
    EMAIL_HELP: 'Valid email format required if provided',
    ADMISSION_HELP: 'Leave empty for auto-generation',
    SECTION_HELP: 'Choose the class section for this student',
    CURRENT_YEAR_HELP: 'Current Academic Year',
  },
};

export default STUDENT_MODULE_STRINGS;
