export const TIMETABLE_CONSTS = {
    STATUS: {
        DRAFT: 'Draft',
        PUBLISHED: 'Published',
        DRAFT_UPPER: 'DRAFT',
        PUBLISHED_UPPER: 'PUBLISHED',
        PENDING: 'PENDING',
        CONFIRMED: 'CONFIRMED',
        CANCELLED: 'CANCELLED',
    },
    COLORS: {
        SUBJECT_MAP: {
            MATH: { color: 'text-blue-600', dot: 'bg-blue-500', border: 'border-blue-200', bg: 'bg-blue-50', hex: '#2563eb', hexBg: '#eff6ff', hexDot: '#3b82f6' },
            ENG: { color: 'text-green-600', dot: 'bg-green-500', border: 'border-green-200', bg: 'bg-green-50', hex: '#16a34a', hexBg: '#f0fdf4', hexDot: '#22c55e' },
            SCI: { color: 'text-yellow-600', dot: 'bg-yellow-400', border: 'border-yellow-200', bg: 'bg-yellow-50', hex: '#ca8a04', hexBg: '#fefce8', hexDot: '#eab308' },
            HIN: { color: 'text-purple-600', dot: 'bg-purple-500', border: 'border-purple-200', bg: 'bg-purple-50', hex: '#7c3aed', hexBg: '#f5f3ff', hexDot: '#8b5cf6' },
            SST: { color: 'text-orange-600', dot: 'bg-orange-400', border: 'border-orange-200', bg: 'bg-orange-50', hex: '#ea580c', hexBg: '#fff7ed', hexDot: '#f97316' },
            COMP: { color: 'text-teal-600', dot: 'bg-teal-500', border: 'border-teal-200', bg: 'bg-teal-50', hex: '#0d9488', hexBg: '#f0fdfa', hexDot: '#14b8a6' },
            CS: { color: 'text-teal-600', dot: 'bg-teal-500', border: 'border-teal-200', bg: 'bg-teal-50', hex: '#0d9488', hexBg: '#f0fdfa', hexDot: '#14b8a6' },
            PE: { color: 'text-red-600', dot: 'bg-red-500', border: 'border-red-200', bg: 'bg-red-50', hex: '#dc2626', hexBg: '#fef2f2', hexDot: '#ef4444' },
            DRAW: { color: 'text-indigo-600', dot: 'bg-indigo-500', border: 'border-indigo-200', bg: 'bg-indigo-50', hex: '#4f46e5', hexBg: '#eef2ff', hexDot: '#6366f1' },
            BIO: { color: 'text-emerald-600', dot: 'bg-emerald-500', border: 'border-emerald-200', bg: 'bg-emerald-50', hex: '#059669', hexBg: '#ecfdf5', hexDot: '#10b981' },
            CHEM: { color: 'text-pink-600', dot: 'bg-pink-500', border: 'border-pink-200', bg: 'bg-pink-50', hex: '#db2777', hexBg: '#fdf2f8', hexDot: '#ec4899' },
            PHY: { color: 'text-sky-600', dot: 'bg-sky-500', border: 'border-sky-200', bg: 'bg-sky-50', hex: '#0284c7', hexBg: '#f0f9ff', hexDot: '#0ea5e9' },
            GEO: { color: 'text-lime-600', dot: 'bg-lime-500', border: 'border-lime-200', bg: 'bg-lime-50', hex: '#65a30d', hexBg: '#f7fee7', hexDot: '#84cc16' },
            HIST: { color: 'text-amber-600', dot: 'bg-amber-500', border: 'border-amber-200', bg: 'bg-amber-50', hex: '#b45309', hexBg: '#fffbeb', hexDot: '#f59e0b' },
        },
        SUBJECT_POOL: [
            { color: 'text-blue-600', dot: 'bg-blue-500', border: 'border-blue-200', bg: 'bg-blue-50', hex: '#2563eb', hexBg: '#eff6ff', hexDot: '#3b82f6' },
            { color: 'text-green-600', dot: 'bg-green-500', border: 'border-green-200', bg: 'bg-green-50', hex: '#16a34a', hexBg: '#f0fdf4', hexDot: '#22c55e' },
            { color: 'text-purple-600', dot: 'bg-purple-500', border: 'border-purple-200', bg: 'bg-purple-50', hex: '#7c3aed', hexBg: '#f5f3ff', hexDot: '#8b5cf6' },
            { color: 'text-orange-600', dot: 'bg-orange-400', border: 'border-orange-200', bg: 'bg-orange-50', hex: '#ea580c', hexBg: '#fff7ed', hexDot: '#f97316' },
            { color: 'text-teal-600', dot: 'bg-teal-500', border: 'border-teal-200', bg: 'bg-teal-50', hex: '#0d9488', hexBg: '#f0fdfa', hexDot: '#14b8a6' },
            { color: 'text-red-600', dot: 'bg-red-500', border: 'border-red-200', bg: 'bg-red-50', hex: '#dc2626', hexBg: '#fef2f2', hexDot: '#ef4444' },
            { color: 'text-indigo-600', dot: 'bg-indigo-500', border: 'border-indigo-200', bg: 'bg-indigo-50', hex: '#4f46e5', hexBg: '#eef2ff', hexDot: '#6366f1' },
            { color: 'text-pink-600', dot: 'bg-pink-500', border: 'border-pink-200', bg: 'bg-pink-50', hex: '#db2777', hexBg: '#fdf2f8', hexDot: '#ec4899' },
            { color: 'text-sky-600', dot: 'bg-sky-500', border: 'border-sky-200', bg: 'bg-sky-50', hex: '#0284c7', hexBg: '#f0f9ff', hexDot: '#0ea5e9' },
            { color: 'text-amber-600', dot: 'bg-amber-500', border: 'border-amber-200', bg: 'bg-amber-50', hex: '#b45309', hexBg: '#fffbeb', hexDot: '#f59e0b' },
        ],
        TEACHER_MAP: {
            'Kavita Rao': 'bg-pink-500', 'Rajesh Kumar': 'bg-blue-500',
            'Priya Patel': 'bg-orange-500', 'Meena Sharma': 'bg-green-500',
            'Suresh Nair': 'bg-purple-500', 'Anjali Singh': 'bg-amber-500',
            'Amit Joshi': 'bg-cyan-500', 'Vikas Mishra': 'bg-rose-500',
        },
        AVATAR_POOL: [
            { bg: '#e0f2fe', text: '#0369a1' },
            { bg: '#dcfce7', text: '#15803d' },
            { bg: '#ede9fe', text: '#6d28d9' },
            { bg: '#fef3c7', text: '#92400e' },
            { bg: '#fce7f3', text: '#9d174d' },
            { bg: '#f0fdf4', text: '#166534' },
            { bg: '#fff1f2', text: '#be123c' },
            { bg: '#f0f9ff', text: '#0c4a6e' },
        ],
    },
    MESSAGES: {
        ERR_LOAD_DATA: 'Failed to load timetable data',
        ERR_SAVE_SLOT: 'Failed to save slot',
        SUCC_SLOT_SAVED: 'Slot saved ✓',
        ERR_REMOVE_SLOT: 'Failed to remove slot',
        SUCC_SLOT_REMOVED: 'Slot removed',
        ERR_AUTO_FILL: 'Auto-fill failed',
        SUCC_AUTO_FILL: (count) => `Auto-filled ${count ?? ''} slots`,
        ERR_CLEAR_ALL: 'Failed to clear slots',
        SUCC_CLEAR_ALL: 'All slots cleared',
        ERR_PUBLISH: 'Failed to publish',
        SUCC_PUBLISHED: 'Timetable published ✓',
        ERR_SAVE_ALL: 'Failed to save slots',
        SUCC_SAVE_ALL: 'All slots saved ✓',
        ERR_LOAD_TT: 'Failed to load timetables',
        ERR_CREATE_TT: 'Failed to create timetable',
        SUCC_CREATE_TT: 'Timetable created successfully',
        SUCC_PUBLISH_TT: 'Published successfully',
        ERR_DEL_TT: 'Failed to delete',
        SUCC_DEL_TT: 'Deleted successfully',
        ERR_LOAD_SUBJ: 'Failed to load subjects.',
        ERR_SAVE_TEACHER: 'Failed to assign teacher',
        SUCC_SAVE_TEACHER: 'Teacher assigned ✓',
        ERR_DEL_FAIL: 'Delete failed. Please try again.',
        ERR_OP_FAIL: 'Operation failed. Please try again.'
    },
    CREATE_SCHEDULE: {
        BANNER_DRAFT_TEXT: 'This timetable is in ',
        BANNER_DRAFT_STRONG: 'DRAFT',
        BANNER_DRAFT_END: ' mode. Review and publish when ready.',
        BTN_PUBLISH_NOW: 'Publish Now',
        BTN_DISMISS: 'Dismiss',
        BTN_BACK: 'Back',
        VIEW_MODE: 'View',
        TAB_PLANNER: 'Planner',
        TAB_ANALYTICS: 'Analytics',
        BTN_AUTO_FILL: 'Auto-fill',
        BTN_SAVE_ALL: 'Save All',
        BTN_SAVING: 'Saving...',
        BTN_SETTINGS: 'Settings',
        BTN_PUBLISH: 'Publish',
        BTN_PRINT: 'Print',
        LBL_WORKING_DAYS: 'Working Days',
        LBL_PERIODS_DAY: 'Periods / Day',
        LBL_SLOTS_FILLED: 'Slots Filled',
        LBL_EMPTY_SLOTS: 'Empty Slots',
        LBL_TEACHERS: 'Teachers',
        BTN_SUBSTITUTE: 'Substitute',
        BTN_SUBSTITUTE_COUNT: (count) => `Substitute (${count})`,
        BTN_PENDING: 'Pending',
        BTN_SUB_PANEL: 'Subjects Panel',
        FILTER_ALL: 'All',
        BTN_CLEAR_ALL: 'Clear All',
        LOADING_TT: 'Loading timetable...',
        TH_PERIOD_TIME: 'PERIOD / TIME',
        CONFIRM_PUB_TITLE: 'Publish Timetable?',
        CONFIRM_PUB_MSG1: 'This will make the timetable visible to all students and teachers for ',
        CONFIRM_PUB_CANCEL: 'Cancel',
        CONFIRM_PUB_YES: 'Yes, Publish',
        TOOLTIP_EDIT: 'Edit Slot',
        TOOLTIP_TEACHER: 'Change Teacher',
        TOOLTIP_REMOVE: 'Remove Slot',
        DRAG_EMPTY: 'Click empty slot to add subjects'
    },
    DIRECTORY: {
        TITLE: 'Timetable Directory',
        SUBTITLE: 'List of all class-section timetables. Choose view or edit.',
        CARD_TOTAL: 'Total',
        CARD_PUB: 'Published',
        CARD_DRAFT: 'Draft',
        QUICK_ACTIONS: 'Quick Actions',
        BTN_ADD_TT: 'Add Timetable',
        BTN_TEACHER_SCH: 'Teacher Schedule',
        BTN_CONFIG: 'School Time Config',
        PH_SEARCH: 'Search class...',
        FILTER_STATUS_ALL: 'All Status',
        FILTER_CLASS_ALL: 'All Class',
        FILTER_YEAR_ALL: 'All Years',
        TABLE_HEADERS: ['CLASS', 'SECTION', 'STATUS', 'LAST UPDATED', 'ACTIONS'],
        LOADING: 'Loading timetables...',
        NO_TT: 'No timetables found',
        BTN_VIEW: 'View',
        BTN_EDIT: 'Edit',
        BTN_PUBLISHING: 'Publishing...',
        BTN_PUBLISH: 'Publish',
        BTN_DELETE: 'Delete',
        CONFIRM_DEL_TITLE: 'Delete Timetable?',
        CONFIRM_DEL_MSG: 'This action cannot be undone. All slots will be permanently removed.',
        BTN_CANCEL: 'Cancel',
        BTN_DELETING: 'Deleting...',
        LBL_JUST_NOW: 'Just now',
        LBL_RECENTLY: 'Recently',
        ERR_LOAD_YEARS: 'Failed to load academic years:',
        ERR_LOAD_CLASSES: 'Failed to load active classes:'
    },
    ADD_SLOT: {
        ROOMS: ['101', '102', 'Lab 1', 'Art', 'GRD'],
        TITLE_EDIT: 'Edit Slot',
        TITLE_ADD: 'Add Slot',
        LBL_SUBJECT: 'Subject',
        PH_SEARCH_SUBJ: 'Search subject…',
        LBL_LOADING: 'Loading…',
        BTN_RETRY: 'Retry',
        NO_SUBJECTS: 'No subjects found',
        NO_MATCH: (q) => `No match for "${q}"`,
        LBL_ROOM: 'Room / Venue',
        PH_ROOM: 'Room…',
        LBL_TEACHER: 'Teacher',
        PH_SEARCH_TEACHER: 'Search by name…',
        LBL_NOT_ASSIGNED: 'Not Assigned',
        LBL_SELECT_SUBJ_FIRST: 'Select a subject first',
        LOADING_TEACHERS: 'Loading teachers…',
        NO_TEACHERS: 'No teachers found',
        LBL_BEST_MATCH: '⭐ Best Match',
        LBL_OTHERS: 'Others',
        LBL_BUSY: '🔴 Busy (Conflict)',
        BTN_CANCEL: 'Cancel',
        BTN_SAVING: 'Saving…',
        BTN_UPDATE: 'Update Slot',
        BTN_ADD: 'Add Slot',
        ERR_NO_SUBJ: 'Please select a subject.',
        SUCC_ASSIGNED: (name) => `Assigned to ${name}`,
        SUCC_UNASSIGNED: 'Teacher unassigned',
        ERR_SAVE_FAIL: 'Failed to save. Please try again.'
    },
    ADD_TT_MODAL: {
        TITLE: 'New Timetable Schedule',
        LBL_CLASS: 'Class',
        PH_SEL_CLASS: '— Select Class —',
        PH_LOAD_CLASS: 'Loading...',
        LBL_SEC: 'Section',
        PH_SEL_SEC_FIRST: '— Select Class first —',
        PH_NO_SEC: 'No sections found',
        PH_SEL_SEC: '— Select Section —',
        LBL_YEAR: 'Academic Year',
        PH_SEL_YEAR: '— Select Academic Year —',
        LBL_CURRENT_YEAR: ' (Current Year)',
        LBL_COPY: 'Copy Schedule From',
        LBL_OPTIONAL: '(optional)',
        PH_START_EMPTY: '– Start empty –',
        LBL_NOTES: 'Notes',
        PH_NOTES: 'Any remarks...',
        BTN_CANCEL: 'Cancel',
        BTN_CREATING: 'Creating...',
        BTN_CREATE: 'Create Schedule',
        ERR_REQ_CLASS: 'Class is required',
        ERR_REQ_SEC: 'Section is required',
        ERR_REQ_YEAR: 'Academic year is required'
    },
    ANALYTICS: {
        LBL_LOADING: 'Loading analytics…',
        LBL_ERR: 'Error: ',
        LBL_COMPLETION: 'Completion',
        LBL_FILLED: 'filled',
        LBL_ON_TARGET: 'On target',
        LBL_BEHIND: 'behind',
        LBL_EMPTY_SLOTS: 'Empty slots',
        LBL_AUTO_RES: 'Auto-fill can resolve',
        LBL_OVERLOADED: 'Overloaded',
        LBL_ABOVE_PW: 'Above ',
        LBL_PW: '/week',
        CHART_FILLED: 'FILLED',
        CHART_EMPTY: 'EMPTY',
        CHART_TOTAL: 'TOTAL',
        SUGG_TITLE: '⚡ Suggestions',
        SUGG_AUTO: (count) => `Use Auto-fill to place ${count} remaining slot${count > 1 ? 's' : ''}.`,
        SUGG_PRIO: (code, diff) => `Prioritize ${code} — ${diff} period${diff > 1 ? 's' : ''} behind target.`,
        SUGG_OVER: (count, max) => `${count} teacher${count > 1 ? 's' : ''} exceed ${max} periods/week.`,
        TAB_COVERAGE: '📘 Subject coverage',
        TAB_LOAD: '👥 Teacher load',
        NO_SUBJ: 'No subjects available.',
        UNNAMED: 'Unnamed',
        NO_TEACHER: 'No teacher data in slots.',
        LBL_OVERLOAD_BADGE: 'Overloaded',
        LBL_PER_WEEK: 'p/w'
    },
    ASSIGN_TEACHER: {
        TITLE: 'Assign Teacher',
        LBL_CURR_ASSIGNED: 'CURRENTLY ASSIGNED',
        LBL_SEL_TEACHER: 'SELECT TEACHER',
        LBL_UNASSIGNED: '— Unassigned —',
        LOADING_TEACHERS: 'Loading teachers…',
        NO_TEACHERS: 'No teachers found',
        LBL_BEST_MATCH: '⭐ Best Match',
        LBL_OTHERS: 'Others',
        LBL_BUSY: '🔴 Busy (Conflict)',
        BTN_CANCEL: 'Cancel',
        BTN_ASSIGNING: 'Assigning…',
        BTN_ASSIGN: 'Assign Teacher',
        ERR_LOAD_FAIL: 'Teacher load failed:'
    },
    PENDING_SUB: {
        TITLE: 'Pending Substitutions',
        LOADING: 'Loading substitutions…',
        NO_SUB: 'No substitutions yet',
        NO_SUB_DESC: 'Arranged substitutions appear here',
        BTN_CONFIRM: 'Confirm',
        BTN_CANCEL: 'Cancel',
        BTN_CLOSE: 'Close'
    },
    PRINT_TT: {
        TITLE_PREVIEW: 'Print Preview',
        LBL_A4: 'A4 Landscape',
        BTN_PRINT: 'Print',
        DOC_TITLE: 'CLASS TIMETABLE',
        LBL_YEAR: 'Academic Year:',
        LBL_SEC: 'Section:',
        LBL_DRAFT: 'DRAFT',
        META_DAYS: 'Working Days',
        META_PERIODS: 'Periods/Day',
        META_START: 'Start:',
        META_DUR: 'Duration:',
        META_MIN: 'min',
        META_FILLED: 'Filled:',
        TH_PERIOD: 'PERIOD',
        LEGEND_TITLE: 'SUBJECT LEGEND',
        LEGEND_SLOTS: 'slots',
        FOOTER_GEN: 'Generated on ',
        FOOTER_TOTAL: 'Total:',
        FOOTER_COMP: 'complete'
    },
    CONFIG: {
        SUCC_SAVE: 'Configuration saved successfully.',
        ERR_SAVE: 'Failed to save configuration.',
        ERR_PERIOD_RANGE: (min, max) => `Must be between ${min} and ${max} periods.`,
        ERR_DUR_RANGE: (min, max) => `Period duration must be between ${min} and ${max} minutes.`,
        ERR_MIN_MIN: (min) => `Min ${min} min.`,
        ERR_MAX_MIN: (max) => `Max ${max} min.`,
        ERR_REQ_DAY: 'Select at least one working day.',
        ERR_REQ_ENTER: (min, max) => `Required. Enter ${min}–${max}.`,
        ERR_MIN_PERIOD: (min) => `Minimum is ${min} period.`,
        ERR_REQ_ENTER_MIN: (min, max) => `Required. Enter ${min}–${max} min.`,
        ERR_MIN_DUR: (min) => `Min period duration is ${min} minutes.`,
        TITLE: 'School Time Configuration',
        LOADING: 'Loading configuration…',
        LBL_YEAR: 'ACADEMIC YEAR',
        PH_LOAD_YEAR: 'Loading…',
        PH_NO_YEAR: 'No academic years found',
        LBL_CUR_YEAR: ' (Current)',
        BADGE_CUR_YEAR: 'Current',
        LBL_DAYS: 'WORKING DAYS',
        LBL_PERIODS: 'PERIOD SETTINGS',
        LBL_START_TIME: 'Start Time',
        LBL_PERIOD_DAY: 'Periods / Day',
        LBL_MAX_PAREN: (max) => `(max ${max})`,
        LBL_DUR: 'Period Duration (min)',
        LBL_DUR_PAREN: (min, max) => `(${min}–${max} min)`,
        LBL_BREAKS: 'BREAKS',
        LBL_AFTER_PERIOD: 'After Period',
        LBL_AFTER_PAREN: (max) => `(1–${max})`,
        LBL_DUR_MIN: 'Duration (min)',
        BTN_ADD_BREAK: '+ Add Break',
        DEF_BREAK_LABEL: '☕ Break',
        LBL_PREVIEW: 'LIVE SCHEDULE PREVIEW',
        BTN_CANCEL: 'Cancel',
        BTN_SAVING: 'Saving…',
        BTN_SAVE: 'Save Configuration'
    },
    SUBSTITUTION: {
        REASONS: [
            'Medical Leave',
            'Personal Leave',
            'Official Duty',
            'Training / Workshop',
            'Emergency',
            'Other',
        ],
        TITLE_UPDATE: 'Update Substitution',
        TITLE_ARRANGE: 'Arrange Substitution',
        LBL_SEL_SLOT: 'Selected Slot',
        LBL_UNKNOWN_SUBJ: 'Unknown Subject',
        BADGE_PENDING: 'Pending',
        LBL_ORIG_TEACHER: 'Original Teacher',
        LBL_DATE: 'Substitution Date',
        LBL_SUB_TEACHER: 'Substitute Teacher',
        LOADING_TEACHERS: 'Loading available teachers…',
        PH_SEL_TEACHER: 'Select substitute teacher',
        PH_SEARCH_TEACHER: 'Search teacher…',
        NO_TEACHERS: 'No teachers found',
        LBL_REASON: 'Reason',
        PH_SEL_REASON: 'Select reason',
        LBL_SPEC_REASON: 'Specify Reason',
        PH_DESC_REASON: 'Describe the reason (max 100 characters)…',
        LBL_NOTES: 'Additional Notes',
        PH_NOTES: 'Any extra instructions for the substitute…',
        BTN_CANCEL: 'Cancel',
        BTN_SAVING: 'Saving…',
        BTN_UPDATE: 'Update',
        BTN_CONFIRM: 'Confirm',
        ERR_DATE_REQ: 'Date is required',
        ERR_TEACHER_REQ: 'Please select a substitute teacher',
        ERR_TEACHER_SAME: 'Substitute cannot be the same as the original teacher',
        ERR_REASON_REQ: 'Please select a reason',
        ERR_REASON_SPEC: 'Please specify the reason',
        ERR_SUBMIT_GEN: 'Something went wrong',
        OTHER: 'Other'
    },
    TEACHER_SCH_VIEWER: {
        ERR_LOAD_TEACHERS: 'Failed to load teachers. Please try again.',
        ERR_LOAD_SCHEDULE: 'Failed to load schedule. Please try again.',
        TITLE: 'Teacher Schedule Viewer',
        SUBTITLE: "View any teacher's daily period schedule",
        PH_CHOOSE_TEACHER: 'Choose a teacher',
        PH_SEARCH_TEACHER: 'Search teacher…',
        NO_TEACHERS: 'No teachers found',
        LBL_SEL_TEACHER: 'Select Teacher',
        LBL_DATE: 'Date',
        LBL_NON_WORKING: 'Non-working day',
        LBL_NON_WORKING_DESC: 'is not a working day.',
        LBL_NO_PERIODS: 'No periods assigned',
        LBL_NO_PERIODS_DESC: (date) => `has no periods on ${date}.`,
        LBL_WORKING_DAY: 'Working day',
        LBL_PROMPT: 'Select a teacher above to view their schedule',
        BTN_CLOSE: 'Close'
    },
    TT_SETTINGS: {
        TITLE: 'Timetable Settings',
        LBL_LOADING: 'Loading...',
        ERR_SAVE: 'Failed to update settings',
        LBL_CLASS: 'Class',
        LBL_SECTION: 'Section',
        LBL_CANNOT_CHANGE: 'Cannot be changed',
        LBL_YEAR: 'Academic Year',
        LBL_STATUS: 'Status',
        LBL_NOTES: 'Notes',
        PH_NOTES: 'Remarks about this timetable...',
        LBL_DAYS: 'Working Days',
        LBL_DAYS_DESC: '(from School Config)',
        BTN_CANCEL: 'Cancel',
        BTN_SAVING: 'Saving...',
        BTN_APPLY: 'Apply Changes',
        DEF_STATUS: 'Draft'
    }
};