const USER_MANAGEMENT_STRINGS = {
  COMMON: {
    BACK_TO_LIST: 'Back to List',
    GO_BACK: 'Go Back',
    BACK_TO_USERS: 'Back to Users',
    DISCARD: 'Discard',
    DISCARD_CHANGES: 'Discard Changes',
    SAVE_DETAILS: 'Save Details',
    SAVE_CHANGES: 'Save Changes',
    ADDING: 'Adding...',
    SAVING: 'Saving...',
    LOADING_USER: 'Loading Staff...',
    RETRY: 'Retry',
    LOADING: 'Loading Staff...',
    LOADING_PROFILE: 'Loading staff profile details...',
    PROFILE_ERROR: 'Staff profiles could not be loaded or do not exist.',
    NO_USERS_TO_DISPLAY: 'There are no staffs to display.',
    CONTACT: 'Contact:',
    STATUS: 'Status:',
    N_A: 'N/A',
    UNKNOWN: 'Unknown',
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    ACTIVE_LABEL: 'Active',
    INACTIVE_LABEL: 'Inactive',
    YES_CONTINUE: 'Yes, Continue',
    CANCEL: 'Cancel',
  },

  MANAGE_USERS: {
    PAGE_TITLE: 'Manage All Staff',
    PAGE_TOOLTIP: 'Efficiently manage system roles, permissions and account status.',
    SEARCH_PLACEHOLDER: 'Search by name, email or ID..',
    FILTERS: {
      ALL_STATUS: 'All Status',
      ALL_ROLES: 'All Roles',
      ACTIVE: 'ACTIVE',
      INACTIVE: 'INACTIVE',
      ACTIVE_LABEL: 'Active',
      INACTIVE_LABEL: 'Inactive',
    },
    ACTIONS: {
      ADD_USER: 'Add Staff',
      EXPORT_CSV: 'Export CSV',
      VIEW: 'View',
      EDIT: 'Edit',
      DEACTIVATE: 'Deactivate',
      ACTIVATE: 'Activate',
      RESET_PASSWORD: 'Password Reset',
      ROWS_PER_PAGE: 'Rows per page:',
      ROWS: 'Rows:',
      SHOWING: 'Showing',
      TO: 'to',
      OF: 'of',
      PAGE: 'Page',
      OF_TOTAL: 'of',
    },
    TABLE_HEADERS: {
      USER_NAME: 'Staff Name',
      EMP_ID: 'Employee Id',
      EMAIL: 'Email',
      MOBILE: 'Mobile Number',
      STATUS: 'Status',
      ACTIONS: 'Actions',
    },
    CARDS: {
      TOTAL_USERS: 'Total Staffs',
      ACTIVE_USERS: 'Active Staffs',
      INACTIVE_USERS: 'Inactive Staffs',
    },
    MESSAGES: {
      NO_USERS_FOUND: 'No Staffs Found',
      LOADING_USERS: 'Loading staffs ...',
      ERROR_LOADING: 'Error Loading Staffs',
      EXPORT_INFO: 'No staffs on this page to export.',
      RESET_FAILED: 'Reset password failed',
      STATUS_FAILED: 'Status update failed',
      EXPORT_SUCCESS: '✓ Exported {count} staff{plural} — CSV {page} of {totalPages}',
      NO_USERS_DISPLAY: 'There are no staffs to display.',
    },
    CONFIRMATION: {
      TITLE: 'Redirect to Teachers Module',
      MESSAGE: 'You will be redirected to the Teachers Module to manage this teacher. Do you wish to continue?',
      CONFIRM_LABEL: 'Yes, Continue',
      CANCEL_LABEL: 'Cancel',
    },
  },

  USER_VIEW: {
    PAGE_TITLE: 'Staff Profile',
    BACK_TO_LIST: 'Back to List',
    EMPLOYEE_ID: 'Employee ID',
    PERSONAL_DETAILS: 'Personal Details',
    PROFESSIONAL_DETAILS: 'Professional Details',
    SALARY_PAYROLL: 'Salary & Payroll',
    SYSTEM_ELIGIBILITY: 'System Eligibility',
    LOGIN_ACCESS: 'Login Access',
    LOGIN_ACCESS_DESC: 'Authorized for web dashboard',
    ATTENDANCE_ACCESS: 'Attendance Access',
    ATTENDANCE_ACCESS_DESC: 'Enabled for mobile check-in',
    EMAIL_ADDRESS: 'Email Address',
    PHONE_NUMBER: 'Phone Number',
    RESIDENTIAL_ADDRESS: 'Residential Address',
    DATE_OF_BIRTH: 'Date of Birth',
    HIGHEST_QUALIFICATION: 'Highest Qualification',
    YEARS_OF_EXPERIENCE: 'Years of Experience',
    SALARY_TYPE: 'Salary Type',
    JOINED_DATE: 'Joined Date',
    BASIC_SALARY: 'Basic Salary',
    PAYROLL_STATUS: 'Payroll Status',
  },

  EDIT_USER: {
    PAGE_TITLE: 'Edit Staff: {name}',
    PAGE_SUBTITLE: 'Manage personal information and account status for staff.',
    PROFILE_PHOTO: 'Profile Photo',
    PROFILE_PHOTO_HELP: '(optional)',
    CLICK_TO_UPLOAD: 'Click to upload photo',
    UPLOAD_HELP: 'JPEG or PNG, max 10 MB',
    CURRENT_PROFILE: 'Current profile photo',
    CHANGE: 'Change',
    NEW_PHOTO_SELECTED: 'new photo selected',
    PERSONAL_DETAILS: 'Personal Details',
    PERSONAL_SHORT: 'Personal',
    SAVE_BUTTON: 'Save Details',
    BACK_TO_LIST: 'Back to List',
    LOADING: 'Loading Staff...',
    UPDATE_LOADING: 'Updating staff...',
    SUCCESS_MESSAGE: "{name}'s details updated successfully! ✅",
    PHOTO_REFLECT: 'Profile photo may take a few seconds to reflect.',
    DISCARD_CHANGES: 'Discard Changes',
    SAVE_CHANGES: 'Save Changes',
  },

  ADD_USER: {
    PAGE_TITLE: 'Add New Staff',
    PAGE_SUBTITLE: 'Enter the details below to onboard a new staff member into the system.',
    PROFILE_PHOTO: 'Profile Photo',
    PROFILE_PHOTO_HELP: '(optional)',
    CLICK_TO_UPLOAD: 'Click to upload photo',
    UPLOAD_HELP: 'JPEG or PNG, max 10 MB',
    PERSONAL_DETAILS: 'Personal Details',
    PERSONAL_SHORT: 'Personal',
    BACK_TO_LIST: 'Back to List',
  },
};

export const MANAGE_USERS_STRINGS = USER_MANAGEMENT_STRINGS.MANAGE_USERS;
export default USER_MANAGEMENT_STRINGS;